### ISSUE TITLE
doesn't pass the current IP address correctly 

### ISSUE THREAD

**Issue by slav123** [patoroco/doorkeeper#27]
It doesn't seem to work - it doesn't pass the current IP address to rules correctly 
```
Current IP: 20.168.60.70
----------------------
Firewall Inbound Rules (original)
----------------------
22::tcp - undefined
80::tcp - 0.0.0.0/0,::/0
443::tcp - 0.0.0.0/0,::/0
----------------------
Firewall Inbound Rules (updated)
----------------------
22::tcp - undefined
80::tcp - 0.0.0.0/0,::/0
443::tcp - 0.0.0.0/0,::/0
:: - undefined
(node:3762) UnhandledPromiseRejectionWarning: Error: Request failed with status code 422
    at createError (/home/runner/work/_actions/patoroco/doorkeeper/master/dist/index.js:13527:15)
    at settle (/home/runner/work/_actions/patoroco/doorkeeper/master/dist/index.js:10066:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/patoroco/doorkeeper/master/dist/index.js:11284:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:3762) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3762) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lunswor** [comment]
Been using version 0.3.0 successfully for a few months but just started getting the same error as above but with status code 401
